//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualVacationRight
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public Nullable<decimal> DaysCumulated { get; set; }
        public Nullable<decimal> DaysUsed { get; set; }
        public string Remarks { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
