//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public int CategoryID { get; set; }
        public string DocumentCode { get; set; }
        public string SourceID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string DocImagePath { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
