//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacationTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.AnnualVacationRights = new HashSet<AnnualVacationRight>();
            this.VacationRequests = new HashSet<VacationRequest>();
        }
    
        public int PersonID { get; set; }
        public string PersonType { get; set; }
        public string Corporation { get; set; }
        public string PersonCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string SSN { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string isManager { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public Nullable<decimal> Compensation { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AccumulatedSickDays { get; set; }
        public Nullable<decimal> AccumulatedVacation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnualVacationRight> AnnualVacationRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationRequest> VacationRequests { get; set; }
    }
}
